### ISSUE TITLE
vigra build with boost 1.72

### ISSUE THREAD

**Issue by k-dominik** [conda-forge/vigra-feedstock#62]
Hi!

this might be a silly one, but I was wondering why the latest vigra builds (1012 and up) have been built with boost `1.72` whereas the current conda-forge pinning on boost is `1.70`?

https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/9898f7005d1aabb811e4aba38ece5b3003f4f160/recipe/conda_build_config.yaml#L347-L348

**Comment by stuarteberg** [comment]
Yeah, this is not an obvious thing to discover naturally.  I'm not an expert, but here's my understanding of what's going on, as far as I can tell:

When conda-forge wants to upgrade the pinning feedstock, they start a process called a "migration", in which the bot opens a PR onto every feedstock that needs to be updated for the new pinning.  The bot adds a file to the `migrations` directory, which changes the pinning for the current feedstock (only).  Here's vigra's migrations directory:

https://github.com/conda-forge/vigra-feedstock/tree/master/.ci_support/migrations

You can inspect the status of a particular "migration" (e.g. boost-1.72) for across all feedstocks by browsing the conda-forge status page:

https://conda-forge.org/status/

It's not a great UI, but if you click on on the purple buttons, you can see the lists of feedstocks which are affected by each migration, in various stages of the process.

I'm not sure how the core team decides when a "migration" is complete and the pinning feedstock can finally be officially updated.  (Does every feedstock need to be in the "done" state?  Or do they just let a few remain in the failed state if their maintainers aren't fixing it after a while?)  Maybe that is somewhere explained in the [conda-forge documentation][1], or maybe one of the [CFEP documents][2].  I haven't checked.

[1]: https://conda-forge.org/docs/
[2]: https://github.com/conda-forge/cfep

**Comment by k-dominik** [comment]
Hi @stuarteberg,

thank you very much for taking the time to write up this answer. Sadly enough I have already read [CFEP9](https://github.com/conda-forge/cfep/blob/master/cfep-09.md) but didn't make the connection. It would be great if, during migration, packages would be built with the "old" pin as well, to be able to still profit from upstream changes.. But for this migration would have to happen in a branch.

I'm closing this issue a little wiser ;)

Cheers!

**Comment by stuarteberg** [comment]
>It would be great if, during migration, packages would be built with the "old" pin as well, to be able to still profit from upstream changes.. But for this migration would have to happen in a branch.

If you need such a branch for vigra, let me know.  I'll create a new branch, and then you can create a PR against it with the appropriate changes.

Or perhaps even easier would be to simply add you as a maintainer to this feedstock, in which case you can create the branch yourself.  If you don't mind that, then just open a PR that adds your name to the maintainers list, and I'll merge it.

**Comment by k-dominik** [comment]
> Or perhaps even easier would be to simply add you as a maintainer to this feedstock, in which case you can create the branch yourself. If you don't mind that, then just open a PR that adds your name to the maintainers list, and I'll merge it.

just so that I understand this correctly, once I am a maintainer I could create a 'boost-1.70` branch (probably branching off before migration has happened), cherry pick niceties - with whatever being merged into this branch will end up on conda-forge? Are there guidelines wrt to build numbers and the likes (i guess one wouldn't want to clash with the master builds).

**Comment by stuarteberg** [comment]
Yes, all branches are built and their build artifacts are published to conda-forge. For that reason, it is crucial not to create throw-away branches, for example. 

Since the package names include a hash that incorporates the dependency info, I think conflicts are not an issue. But I suppose a special build number (e.g. 2000) might make it easier for us to see which tarballs are which.

https://anaconda.org/conda-forge/vigra/files

(On a related point, we ought to reset the main build number back to 0 whenever a new version of vigra is released.)

As for how to create the branch, it might be easiest to branch from master and explicitly remove the migration file, change the build number, and re-render the feedstock. At least, I *think* that’s the right way. You may want to have a look at the hdf5 pinning, too. If you need to remove that, maybe the branch could be named “no-migrations”? No strong opinions.



conda install conda-smithy
conda smithy rerender -c auto
git push ......

**Comment by stuarteberg** [comment]
To clarify: you should not push to the conda-forge repo directly. You should push to your own fork and make a PR from there into the new branch. I’m currently typing from my phone, but later tonight I can give more specific example commands if that would be helpful.

**Comment by k-dominik** [comment]
I think I know the drill :) thank you very much Stuart! :)

**Comment by jakirkham** [comment]
It might be easier to actually add both builds in the same branch instead of having 2 branches. Can do this by adding a `conda_build_config.yaml` to the `recipe` director with a `boost_cpp` [variant]( https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#build-variants ) listing the versions one wants to build for. As an example, we might have something like this...

```
boost_cpp:
  - 1.70.0
  - 1.72.0
```

Would make sure to re-render after making this change. Conda-smithy should add in all the appropriate builds to the CI matrix.

**Comment by k-dominik** [comment]
> It might be easier to actually add both builds in the same branch instead of having 2 branches. Can do this by adding a `conda_build_config.yaml` to the `recipe` director with a `boost_cpp` [variant](https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#build-variants) listing the versions one wants to build for. As an example, we might have something like this...

I see. Thank you @jakirkham for this suggestion. I rebuilt my stack now with the boost `1.72.0` and hdf5 `1.10.6`. It seems like this migration has progressed far enough to cover all our downstream dependencies :pray:

**Comment by jakirkham** [comment]
Of course. Doesn't come up that often, but it's a useful feature when it does. Also another note is that the Conda package hash would differ for the 2 versions. So there is no need to play with the build number to approximate that behavior.

Yeah it's true. A decent amount has been migrated at this point. We've definitely been smoothing out the migration process with each subsequent run through. Migration statuses can be found [on the status page]( https://conda-forge.org/status/ ).

**Comment by stuarteberg** [comment]
@jakirkham Thanks, John! Your suggestion is WAY simpler than mine. 👍

And now Dominik's solution to just upgrade the rest of his stack is simplest of all (well, as far as this feedstock is concerned).

**Comment by stuarteberg** [comment]
[Sorry for the noise, I'm adding a note here for future reference.]

>It might be easier to actually add both builds in the same branch instead of having 2 branches. Can do this by adding a `conda_build_config.yaml` to the `recipe` directory.

I needed to try that in a different recipe today.  It turns out it works IF there is no active "migration" for the dependency you're creating the variant for.  Apparently the configuration in the migration file takes precedence over whatever is in `conda_build_config.yaml`.

So, to create a variant for `boost_cpp` in this feedstock, we'd have to do one of the following:

- Add the variant to `meta.yaml` as shown above and DELETE `.ci_support/migrations/boost172.yaml`.  I'm not sure if that would interfere with the normal "migration" process and/or migration status tracking.

OR

- Maybe it would be possible to add the variant list to the migration file, i.e. to `boost172.yaml`.  I haven't tried this.

**Comment by jakirkham** [comment]
Did you re-render?

**Comment by stuarteberg** [comment]
Yes, locally using `conda smithy`.

**Comment by jakirkham** [comment]
Could you please share the change in a PR? Maybe we can figure out what is going on 🙂
